### ISSUE TITLE
Incorrect escape character for error message

### ISSUE THREAD

**Issue by VirtualHotBar** [a1ive/nwinfo#24]
When outputting in JSON format, the escape character of the error message is incorrect.

"\\" -> "\\\\"

![image](https://github.com/a1ive/nwinfo/assets/96966978/7630342f-40a5-49f5-acb8-1fc2b8e7b47b)

**Comment by a1ive** [comment]
This bug has been fixed in https://github.com/a1ive/nwinfo/commit/556a45e8970144e44fbcc24afc20359d854a5d7c.
Please download the latest build: https://github.com/a1ive/nwinfo/releases/tag/latest
![1](https://github.com/a1ive/nwinfo/assets/10670106/2af16006-c3be-48c2-8379-46607728b246)
