### ISSUE TITLE
U盘或其它设备被占用、拔出后，还不能实时从设备列表中移除原设备信息显示

### ISSUE THREAD

**Issue by zwj4031** [a1ive/nwinfo#28]
1.U盘或其它设备被占用、拔出后，还不能实时从设备列表中移除原设备信息显示
2.另外需求增加鼠标悬停某项目时可以显示详细信息

**Comment by a1ive** [comment]
https://stackoverflow.com/questions/2420131/detect-insertion-of-media-into-a-drive-using-windows-messages
https://stackoverflow.com/questions/23525892/can-i-use-the-win32-setup-api-to-detect-when-usb-devices-have-been-plugged-in-or

**Comment by a1ive** [comment]
https://github.com/a1ive/nwinfo/commit/ac4d32015ca9f9fce7265083ad4f60b7a083e9a9
