### ISSUE TITLE
Disk-Size 这个key 为何会出现 readble和bigInt两种不同

### ISSUE THREAD

**Issue by older-fox** [a1ive/nwinfo#3]
在您发布初版之后，我在笔记本尝试之后，输出的Json文件的Disk-Size键为string ，例如 114.25GB
在通过其他程序调用时，返回的Disk-Size键为int ，例如1125416611
请问这种不同是什么原因导致的？

**Comment by a1ive** [comment]
https://github.com/a1ive/nwinfo/commit/410f34f0015272bfb5cf3243585a1ddcd35806f2
这个 commit 给程序添加了一个开关，默认情况下输出的 JSON 文件里面的一些值的类型为 `number`，如果加上 `--human` 这个参数，输出的类型就是自动做单位换算的 `string`。
`nwinfo.exe --format=JSON --human --disk`
https://github.com/a1ive/nwinfo/blob/410f34f0015272bfb5cf3243585a1ddcd35806f2/nwinfo.c#L16-L32

**Comment by older-fox** [comment]
已了解，另外有无任何打赏或赞助通道？

**Comment by a1ive** [comment]
QQ: 2080877493
