### ISSUE TITLE
Request to take a disk number as parameter in --disk command in CLI

### ISSUE THREAD

**Issue by devdevadev** [a1ive/nwinfo#34]
Hi A1ive...

First thanks for development of nwinfo tool that also works great in winpe environment.

Can you please add an option to take a disk number as a parameter in --disk  command ? So we can display output of only desired Disk number if required in CLI usage.

**nwinfo_x64.exe --human --disk=1 --no-smart**

This command will only display information of Disk 1 as output. So we can get variables as per requirement easily.

Thanks & Regards....

**Comment by steve6375** [comment]
This would be good, so that we can determine if a specific disk is an SSD or not as this is difficult to do unless we use powershell and full OS rather than WinPE.

**Comment by a1ive** [comment]
> nwinfo_x64.exe --human --disk=1 --no-smart
> This command will only display information of Disk 1 as output.

This parameter is ambiguous.
Windows counts disks starting from 0, so "Disk 1" could be considered either the first disk (DISK0) or the second disk (DISK1).
Besides, "Disk 1" could refer to "\\\\.\PhysicalDrive0" or "\\\\.\CdRom0" (or even a floppy disk).

I prefer using the format `nwinfo --disk=\\.\PhysicalDrive0` to display information for a specified disk. This way, there is no ambiguity.

**Comment by a1ive** [comment]
@devdevadev You can now download and test: https://github.com/a1ive/nwinfo/releases/tag/latest
Example usage: "nwinfo_x64 --disk=\.\PhysicalDrive0 --no-smart".

**Comment by steve6375** [comment]
![image](https://github.com/a1ive/nwinfo/assets/1469350/ab798ee5-af98-4f49-aa12-de49fb646a66)
Looks good under Win10 x64

**Comment by a1ive** [comment]
> ![image](https://private-user-images.githubusercontent.com/1469350/300179265-ab798ee5-af98-4f49-aa12-de49fb646a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDkyODMsIm5iZiI6MTcwNjQ0ODk4MywicGF0aCI6Ii8xNDY5MzUwLzMwMDE3OTI2NS1hYjc5OGVlNS1hZjk4LTRmNDktYWExMi1kZTQ5ZmI2NDZhNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTMzNjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBhYTljYzUzMzAxMmM1ZTVjZDE5MmVjNDM4YmVmYjRjZjYyOTMyNTRiODBkNmMxNWNkNWE0OGYzODNkZTFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p_g--7excSMwkDazZ416Qhvp2RfWPaidJP5fFhREipg) Looks good under Win10 x64

When S.M.A.R.T. detection is disabled (by adding the `--no-smart` option), nwinfo determines whether the disk is an SSD by querying for the [seek penalty descriptor](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-device_seek_penalty_descriptor), supporting systems from Windows 7 and above.
When S.M.A.R.T. detection is enabled, it invokes the CrystalDiskInfo API (integrated into libcdi.*.dll) to determine whether it's an SSD, which is more accurate but slower.

**Comment by steve6375** [comment]
Thanks. I have written a quick blog article
https://rmprepusb.blogspot.com/2024/01/a-useful-system-information-utility-for.html
Hope its OK?

**Comment by devdevadev** [comment]
Thanks for considering the disknumber as parameter in --disk command. I will remove --no-smart so I can get more accurate info about SSD Drives.

As you said nwinfo use CrystalDiskInfo API by default. Will it be possible for nwinfo to measure random-reads of an unformatted disk and output result to console ? So can know which SSD is more faster. and can create a SSD Disk list as per decending speed order. 

Thanks & Regards...

**Comment by a1ive** [comment]
> Thanks. I have written a quick blog article https://rmprepusb.blogspot.com/2024/01/a-useful-system-information-utility-for.html Hope its OK?


Thanks for your article. The drivers (*.sys) included in the release files are on Microsoft's blacklist, so they may trigger antivirus alerts. If you have concerns, you can delete them, but it will result in the inability to access CPU temperature, voltage, power consumption, ACPI tables, and SPD information, without affecting other functionalities. Other files can also be deleted as needed, without affecting the use of CLI / GUI programs.

**Comment by a1ive** [comment]
> Will it be possible for nwinfo to measure random-reads of an unformatted/formatted disk and output result to console ?

> Will it be possible for nwinfo to measure random-reads of an unformatted/formatted disk and output result to console ?

The feature you mentioned belongs to CrystalDisk**Mark**, not CrystalDiskInfo. You might have confused the two.
