### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tnctr-altay-24** [a1ive/nwinfo#51]
Hello master @a1ive; I'm sorry for opening the issue here, please excuse me as I don't know how to reach you.
I translated your QemuBootTest tool into Turkish. I also adapted the current version. I need your help on something. Please, I wrote a section of the command below, but I was not successful.
Can you please edit the code so that it is successful so that I can make qemu's version information visible on the exe program with the command I want to add?

  SET /P version="%temp%\QemuBootTester\VERSION"
  LABEL qemuVersion,L265T348W90H15,Qemu Versiyon,
  LABEL VersionLabel,L265T364W70H15,%@version%,

When you write the command this way, it shows the file path instead of reading the version information in the VERSION file.

**Comment by a1ive** [comment]
I am not familiar with pecmd syntax and I am not the original author of that program.
You can ask pecmd related questions in this forum (https://pecmd.net/).
